name: Node CI

on: push

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Yarn install
      run: yarn install
    - name: Build source
      run: yarn build
    - name: Run tests
      run: yarn test